# Generated by Django 3.0.4 on 2020-04-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200321_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=255)),
                ('colony', models.CharField(max_length=250)),
                ('postalCode', models.CharField(max_length=10)),
                ('cellPhone', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
