# Generated by Django 3.0.4 on 2020-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=250)),
                ('level', models.IntegerField()),
                ('parent', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'submenu',
            },
        ),
    ]
