# Generated by Django 3.0.4 on 2020-04-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('order', models.CharField(max_length=50)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.submenu')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menu')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
