# Generated by Django 3.0.4 on 2020-04-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='township',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyData.country')),
            ],
            options={
                'db_table': 'township',
            },
        ),
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('web', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyData.township')),
            ],
            options={
                'db_table': 'dealer',
            },
        ),
    ]
