# Generated by Django 3.0.4 on 2020-05-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='city',
            new_name='township',
        ),
    ]
