# Generated by Django 3.0.4 on 2020-05-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyData', '0002_auto_20200430_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='township',
            old_name='zone',
            new_name='country',
        ),
    ]
